# Generated by Django 2.2.5 on 2019-10-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20191023_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='DISCOUNT_RATE',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
