# Generated by Django 2.2.5 on 2019-10-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20191024_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='G', max_length=2, verbose_name=(('B', 'Birthday'), ('A', 'Anniversary'), ('W', 'Wedding'), ('G', 'General'))),
        ),
    ]
