# Generated by Django 2.2.5 on 2019-10-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='occasion',
        ),
    ]
