# Generated by Django 2.2.5 on 2019-10-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20191030_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('B', 'Birthday'), ('A', 'Anniversary'), ('W', 'Wedding'), ('G', 'General')], default='G', max_length=2),
        ),
    ]
