# Generated by Django 2.2.5 on 2019-11-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20191102_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='shopping_cart',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
