# Generated by Django 2.2.5 on 2019-11-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20191104_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_address',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
